[book]
authors = ["Trevor Lovell"]
language = "en"
multilingual = false
src = "src"
title = "bevy_pipe_affect Book"

[preprocessor.keeper]
command = "mdbook-keeper"
after = ["links"]
manifest_dir = "."
externs = ["bevy", "bevy_pipe_affect"]
# be careful about enabling more features as the test builds quickly exceed github runner disk sizes
build_features = ["asset_server", "bevy/bevy_camera", "bevy/bevy_sprite", "bevy/bevy_audio"]
