[book]
authors = ["Trevor Lovell"]
language = "en"
multilingual = false
src = "src"
title = "bevy_pipe_affect Book"

[preprocessor.keeper]
command = "mdbook-keeper"
after = ["links"]
manifest_dir = "."
externs = ["bevy", "bevy_pipe_affect"]
